[package]
name = "rust_port"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_port_lib"
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cty = "0.2.1"
